services:
    zipkin:
        image: openzipkin/zipkin:latest
        restart: always
        ports:
            - '9411:9411'

    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        restart: always
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'

    otel-collector:
        image: otel/opentelemetry-collector:latest
        restart: always
        command: ['--config=/etc/otel-collector-config.yaml']
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - '1888:1888' # pprof extension
            - '8888:8888' # Prometheus metrics exposed by the collector
            - '8889:8889' # Prometheus exporter metrics
            - '13133:13133' # health_check extension
            - '4317:4317' # OTLP gRPC receiver
            - '55679:55679' # zpages extension

    grafana:
        image: grafana/grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin

    servico-a:
        build: ./servico-a
        ports:
            - '8080:8080'
        depends_on:
            - servico-b
            - zipkin
            - prometheus
            - otel-collector

    servico-b:
        build: ./servico-b
        ports:
            - '8081:8081'
        depends_on:
            - zipkin
            - prometheus
            - otel-collector
